# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b56ca3c2cad9b73f0d49436c4c0bdb862ec01079573b81a2ac1b583399c8c5109f486d4e818ca741935715e019092559c6aabc236a9e83ba0cacc17e2e389b97

test:
  secret_key_base: 564587f9198baebebd26e24efb203a6686ef0bf2e3283133f6f2af5686c03fa924d16248320e347068e88b7a7b24365218ad60dfb81ea1765c31de9badba1ae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
